name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.2'
          coverage: none
      - name: Install dependencies
        run: make vendor
      - name: Run tests
        run: make ci
